//wishlist
export const FETCH_WISHLISTS = "FETCH_WISHLISTS"
export const ADD_WISHLIST = "ADD_WISHLIST"
export const ADD_WISHLISTS = "ADD_WISHLISTS"
export const EXAMPLE_WISHLIST = "EXAMPLE_WISHLIST"
export const REMOVE_WISHLIST = "REMOVE_WISHLIST"

//item in wishlist
export const UNSELECT_ITEM = "UNSELECT_ITEM"
export const SELECT_ITEM = "SELECT_ITEM"
export const TOGGLE_ITEM = "TOGGLE_ITEM"

//New Wishlist
export const CREATE_NEW_WISHLIST = "CREATE_NEW_WISHLIST"
export const CLEAR_DRAFT = "CLEAR_DRAFT"
export const CREATE_NEW_ITEM_IN_NEW = "CREATE_NEW_ITEM_IN_NEW"
export const CHANGE_ITEM_NAME_IN_DRAFT = "CHANGE_ITEM_NAME_IN_DRAFT"

export const SAVE_DRAFT_TITLE = "SAVE_DRAFT_TITLE"
export const ADD_WISHLIST_FROM_DRAFT = "ADD_WISHLIST_FROM_DRAFT"

export const DELETE_ITEM_IN_NEW = "DELETE_ITEM_IN_NEW"

//Edit wishlist

export const CREATE_NEW_ITEM_IN_EDIT = "CREATE_NEW_ITEM_IN_EDIT"
export const CHANGE_ITEM_NAME_IN_EDIT = "CHANGE_ITEM_NAME_IN_EDIT"
export const DELETE_ITEM_IN_EDIT = "DELETE_ITEM_IN_EDIT"
export const REROLL_CHANGE_IN_EDIT = "REROLL_CHANGE_IN_EDIT"
export const UPLOAD_EDITTED_WISHLIST = "UPLOAD_EDITTED_WISHLIST"

//View wishlist
export const TOGGLE_ITEM_STATUS = "TOGGLE_ITEM_STATUS"
export const SAVE_AS_PAST = "SAVE_AS_PAST"

//past wishlists
export const ADD_PAST_WISHLISTS = "ADD_PAST_WISHLISTS"