export const SHOW_MENU = "SHOW_MENU"
export const HIDE_MENU = "HIDE_MENU"
export const TOGGLE_MENU = "TOGGLE_MENU"

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION"
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION"
