export const SHOW_MENU = "SHOW_MENU"
export const HIDE_MENU = "HIDE_MENU"
export const TOGGLE_MENU = "TOGGLE_MENU"

export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION"
export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION"

export const JUMP_TO = "JUMP_TO"

//register page
export const SET_REGISTER_VALUE = "SET_REGISTER_VALUE"
export const SET_REGISTER_STATUS = "SET_REGISTER_STATUS"
export const SET_REGISTER_MESSAGE = "SET_REGISTER_MESSAGE"
export const TOGGLE_SHAKE = "TOGGLE_SHAKE"
export const RESET_REGISTER_FORM = "RESET_REGISTER_FORM"
export const SUBMIT_REGISTER_FORM = "SUBMIT_REGISTER_FORM"
export const SET_REGISTER_FORM_STATUS = "SET_REGISTER_FORM_STATUS"

//log in
export const LOGGED_IN = "LOGGED_IN"
export const LOGGED_OUT = "LOGGED_OUT"
export const SET_LOG_IN_MESSAGE = "SET_LOG_IN_MESSAGE"

//loadding
export const FETCHING = "FETCHING"
export const FETCHED = "FETCHED"