export const ADD_NOTIFICATIONS = "ADD_NOTIFICATIONS"
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION"

export const UPLOADING_NOTIFICATION = "UPLOADING_NOTIFICATION"
export const UPLOADED_NOTIFICATION = "UPLOADED_NOTIFICATION"

export const LOADING_NOTIFICATION = "LOADING_NOTIFICATION"
export const LOADED_NOTIFICATION = "LOADED_NOTIFICATION"